# Generated by Django 5.0 on 2024-01-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_create_banner_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
