# Generated by Django 5.0 on 2024-01-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_create_skill_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'Abilities'},
        ),
        migrations.RenameField(
            model_name='skillsection',
            old_name='ability',
            new_name='abilities',
        ),
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
