# Generated by Django 5.0 on 2024-01-01 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_create_user_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('tech_stack', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=13)),
                ('country_name', models.CharField(max_length=30)),
            ],
        ),
    ]
